name: 'publish to dev and medium'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'posts/*'
jobs:
  publish:
    name: publish new article on dev and medium
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: blogpub
        uses: protiumx/blogpub@v0.4.1
        with:
          articles_folder: posts
          devto_api_key: ${{ secrets.DEVTO_TOKEN }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          medium_token: ${{ secrets.MEDIUM_TOKEN }}
          medium_user_id: ${{ secrets.MEDIUM_USER_ID }}
